/* using System;

public class Exception_Handling_1
{
    public static void Main(String[] args)
    {
        try
        {
            int num1, num2,res;
        Console.WriteLine("Enter the num1");
        num1 = int.Parse(Console.ReadLine());
        Console.WriteLine("Enter the num2");
        num2 = int.Parse(Console.ReadLine());
        
        res = num1 / num2;
        Console.WriteLine("The result is :" +res);
          }
        catch(ArithmeticException )
        {
            Console.WriteLine("Invalid division");
        }
        catch(System.FormatException)
        {
            Console.WriteLine("format mismatch");
        }
        catch(Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
        finally
        {
            Console.WriteLine("done");
        }


    }
} */

// C# program to demonstrate the
// IndexOutofRange Exception in array
/*
using System;

public class GFG
{

    // Main Method
    public static void Main(String[] args)
    {
        int[] ar = { 1, 2, 3, 4, 5 };
        try { 
        // causing exception
        for (int i = 0; i <= ar.Length; i++)
            Console.WriteLine(ar[7]);
        }
        catch (IndexOutOfRangeException){
            Console.WriteLine("Array Index is invalid");
        }
        
        
    }
}
*/

using System;

public class GFG
{

    // Main Method
    public static void Main(String[] args)
    {
        string s = "Rahul";
        try
        {
            // causing exception
            for (int i = 0; i <= s.Length; i++)
                Console.WriteLine(s[8]);
        }
        catch (IndexOutOfRangeException)
        {
            Console.WriteLine("Index is invalid");
        }


    }
}

